import { ApiError } from '../../utils/api-error.js';

export const newsletterErrorCodes = {
  CAMPAIGN_INVALID_STATUS: 'CAMPAIGN_INVALID_STATUS',
  CAMPAIGN_NO_RECIPIENTS: 'CAMPAIGN_NO_RECIPIENTS',
  CAMPAIGN_ALREADY_QUEUED: 'CAMPAIGN_ALREADY_QUEUED',
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  CAMPAIGN_EMAIL_SEND_FAILED: 'CAMPAIGN_EMAIL_SEND_FAILED',
  CAMPAIGN_DELIVERY_IN_PROGRESS: 'CAMPAIGN_DELIVERY_IN_PROGRESS',
  CAMPAIGN_INVALID_PAUSE_STATUS: 'CAMPAIGN_INVALID_PAUSE_STATUS',
  CAMPAIGN_INVALID_RESUME_STATUS: 'CAMPAIGN_INVALID_RESUME_STATUS',
  CAMPAIGN_WORKER_UNAVAILABLE: 'CAMPAIGN_WORKER_UNAVAILABLE',
  CAMPAIGN_SMTP_UNAVAILABLE: 'CAMPAIGN_SMTP_UNAVAILABLE',
  CAMPAIGN_AUTO_PAUSED: 'CAMPAIGN_AUTO_PAUSED',
  CAMPAIGN_ACTIVE_DELETE_FORBIDDEN: 'CAMPAIGN_ACTIVE_DELETE_FORBIDDEN',
  SUBSCRIBER_ALREADY_SUBSCRIBED: 'SUBSCRIBER_ALREADY_SUBSCRIBED',
  SUBSCRIBER_RESEND_COOLDOWN: 'SUBSCRIBER_RESEND_COOLDOWN',
  SUBSCRIBER_EMAIL_SEND_FAILED: 'SUBSCRIBER_EMAIL_SEND_FAILED',
  SUBSCRIBER_DELIVERY_IN_PROGRESS: 'SUBSCRIBER_DELIVERY_IN_PROGRESS',
  SUBSCRIBER_PROCESSING_DELIVERY: 'SUBSCRIBER_PROCESSING_DELIVERY',
  SUBSCRIBER_VERIFICATION_COOLDOWN: 'SUBSCRIBER_VERIFICATION_COOLDOWN',
  SUBSCRIBER_RESUBSCRIPTION_COOLDOWN: 'SUBSCRIBER_RESUBSCRIPTION_COOLDOWN',
  SUBSCRIBER_INVALID_STATUS: 'SUBSCRIBER_INVALID_STATUS',
  SUBSCRIBER_NOT_FOUND: 'SUBSCRIBER_NOT_FOUND'
} as const;

export type NewsletterErrorCode = (typeof newsletterErrorCodes)[keyof typeof newsletterErrorCodes];

export function newsletterError(statusCode: number, message: string, code: NewsletterErrorCode): ApiError {
  return new ApiError(statusCode, message, undefined, undefined, { code });
}
