import { generateHTML } from '@tiptap/html';
import StarterKit from '@tiptap/starter-kit';
import Link from '@tiptap/extension-link';
import sanitizeHtml from 'sanitize-html';
import { z } from 'zod';
import { ApiError } from '../../utils/api-error.js';
import { blogTemplateKeys } from './blog-template.registry.js';

export const blogStatuses = ['draft', 'published', 'unpublished', 'trashed'] as const;
export const blogSortFields = ['created_at', 'updated_at', 'published_at', 'title', 'status'] as const;
export const blogSortOrders = ['asc', 'desc'] as const;
export const reservedBlogSlugs = ['create', 'edit', 'new', 'trash', 'preview', 'api', 'admin', 'login'] as const;
const optionalTrimmed = (max: number) => z.string().trim().max(max).optional().nullable().transform((value) => value || null);
const optionalNumericString = z.string().trim().regex(/^\d+$/).optional();
const contentJsonSchema = z.unknown().optional().nullable();
const editorExtensions = [StarterKit.configure({ heading: { levels: [2, 3, 4] }, link: false }), Link.configure({ protocols: ['http', 'https'], openOnClick: false })];
const allowedNodes = new Set(['doc', 'paragraph', 'text', 'heading', 'bulletList', 'orderedList', 'listItem', 'blockquote', 'horizontalRule', 'hardBreak']);
const allowedMarks = new Set(['bold', 'italic', 'link']);
export const createBlogSchema = z.object({ title: z.string().trim().min(3).max(180), slug: z.string().trim().max(191).optional(), excerpt: optionalTrimmed(500), content_json: contentJsonSchema, content_html: z.unknown().optional().nullable(), featured_media_id: optionalNumericString.nullable(), seo_title: optionalTrimmed(70), seo_description: optionalTrimmed(170), canonical_url: z.string().trim().url().max(2048).optional().nullable().transform((value) => value || null), template_key: z.enum(blogTemplateKeys).optional(), blocks_json: z.unknown().optional().nullable() }).strict();
const forbiddenUpdateFields = ['author_id', 'created_by', 'updated_by', 'published_at', 'trashed_at', 'status', 'current_draft_version_id', 'current_published_version_id', 'created_at', 'updated_at'] as const;
export const updateBlogSchema = createBlogSchema.partial().superRefine((value, context) => { for (const field of forbiddenUpdateFields) if (field in value) context.addIssue({ code: 'custom', path: [field], message: `${field} cannot be updated directly` }); if (Object.keys(value).length === 0) context.addIssue({ code: 'custom', message: 'At least one editable field is required' }); });
export const blogListQuerySchema = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).default(20).transform((value) => Math.min(value, 100)), search: z.string().trim().max(120).optional().transform((value) => value || undefined), status: z.enum(blogStatuses).optional(), author_id: optionalNumericString, has_featured_image: z.enum(['true', 'false']).optional(), sort_by: z.enum(blogSortFields).default('updated_at'), sort_order: z.enum(blogSortOrders).default('desc') });
export const blogTrashListQuerySchema = blogListQuerySchema.extend({ sort_by: z.enum(['trashed_at', 'updated_at', 'title']).default('trashed_at') }).omit({ status: true, has_featured_image: true });
export type CreateBlogInput = z.infer<typeof createBlogSchema>; export type UpdateBlogInput = z.infer<typeof updateBlogSchema>; export type BlogListQuery = z.infer<typeof blogListQuerySchema>; export type BlogTrashListQuery = z.infer<typeof blogTrashListQuerySchema>;
export type TipTapDocument = { type: 'doc'; content?: TipTapNode[] }; type TipTapNode = { type: string; text?: string; attrs?: Record<string, unknown>; marks?: Array<{ type: string; attrs?: Record<string, unknown> }>; content?: TipTapNode[] };
function invalid(message: string): never { throw new ApiError(422, message); }
function validHttpUrl(value: unknown): boolean { try { const url = new URL(String(value)); return url.protocol === 'http:' || url.protocol === 'https:'; } catch { return false; } }
function validateNode(node: unknown, isRoot = false): asserts node is TipTapNode { if (!node || typeof node !== 'object' || Array.isArray(node)) invalid('content_json contains an invalid editor node'); const value = node as TipTapNode; if (typeof value.type !== 'string' || !allowedNodes.has(value.type) || (isRoot && value.type !== 'doc')) invalid(`Unsupported editor node: ${String(value.type)}`); if (!isRoot && value.type === 'doc') invalid('Document nodes cannot be nested'); if (value.type === 'text' && typeof value.text !== 'string') invalid('Text nodes require text'); if (value.type === 'heading' && ![2, 3, 4].includes(Number(value.attrs?.level))) invalid('Headings must use levels 2, 3, or 4'); if (value.type !== 'heading' && value.attrs && Object.keys(value.attrs).length) invalid(`Unsupported attributes on ${value.type}`); if (value.marks) { if (!Array.isArray(value.marks)) invalid('Editor marks must be an array'); for (const mark of value.marks) { if (!mark || typeof mark.type !== 'string' || !allowedMarks.has(mark.type)) invalid(`Unsupported editor mark: ${String(mark?.type)}`); if (mark.type === 'link' && !validHttpUrl(mark.attrs?.href)) invalid('Links must use an HTTP or HTTPS URL'); if (mark.type !== 'link' && mark.attrs && Object.keys(mark.attrs).length) invalid(`Unsupported attributes on ${mark.type}`); } } if (value.content !== undefined) { if (!Array.isArray(value.content)) invalid('Editor node content must be an array'); value.content.forEach((child) => validateNode(child)); } }
export function validateBlogEditorJson(value: unknown): TipTapDocument { validateNode(value, true); return value as TipTapDocument; }
export function isBlogContentEmpty(value: unknown): boolean { try { const doc = validateBlogEditorJson(value); const visit = (node: TipTapNode): boolean => Boolean(node.text?.trim()) || Boolean(node.content?.some(visit)); return !visit(doc); } catch { return true; } }
export function generateBlogHtmlFromJson(value: unknown): string { return generateHTML(validateBlogEditorJson(value), editorExtensions); }
export function sanitizeGeneratedBlogHtml(value: string): string { return sanitizeHtml(value, { allowedTags: ['p', 'br', 'strong', 'em', 'ol', 'ul', 'li', 'a', 'blockquote', 'h2', 'h3', 'h4', 'hr'], allowedAttributes: { a: ['href', 'target', 'rel'] }, allowedSchemes: ['http', 'https'], transformTags: { a: sanitizeHtml.simpleTransform('a', { rel: 'noopener noreferrer' }, true) } }); }
export function sanitizeBlogHtml(value?: string | null): string | null { return value ? sanitizeGeneratedBlogHtml(value) : null; }
export function normalizeBlogSlug(input: string): string { const slug = input.trim().toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-').replace(/^-|-$/g, ''); if (!slug) throw new ApiError(422, 'Blog slug is required'); if (reservedBlogSlugs.includes(slug as (typeof reservedBlogSlugs)[number])) throw new ApiError(409, 'Blog slug is reserved'); return slug; }
